### ISSUE TITLE
Add support for Visual Studio "15" Preview

### ISSUE THREAD

**Issue by m0sa** [Therena/ConEmuIntegration#1]
VS "15" Preview 1 and 2 have been around for a while now, and people are starting to switch over. Can you please add support for those too?

**Comment by Therena** [comment]
Hi,

now it is also availible for VS15.
Unfortunatelly I haven't had the time to test it with all versions of VS15.
Additionally is VS15 still in preview state.

So it could be that the extension still not completly support VS15.
If you find something which doesn't work please let me know.

Regards,
David
