### ISSUE TITLE
Add "Open folder in ConEmu" menu entry for "Open folder" Visual Studio option

### ISSUE THREAD

**Issue by bmgandre** [Therena/ConEmuIntegration#12]
### Installed product versions
- Visual Studio: 2017, Version 15.6.4
- This extension: 2.0.0.16
- ConEmu build: 180409 x64
- OS version: Windows 10 Home Single Language, Version 1709, Build 16299.334, x64

### Problem description

"Open folder in ConEmu" is currently available only when a project/solution is opened.
Please add this option also for "Open Folder".

### Steps to recreate

1. Open VS 2017
2. File -> Open -> Folder
3. Right click on any Folder on "Solution Explorer"

### Current behavior

No option for open folder in ConEmu is displayed.

### Expected behavior

Show "Open folder in ComEmu" menu entry.

### Additional files

![folder](https://user-images.githubusercontent.com/11844640/38532184-fdccbaec-3c49-11e8-9d12-4dc804c040d7.gif)

**Comment by Therena** [comment]
Nice idea, thanks.
I will try to add this with one of the next releases.
Will start with some investigation in that to see how this could be implemented.

**Comment by Therena** [comment]
Found a way to get the item in the context menu of the folder view of solution explorer:
![contextmenu](https://user-images.githubusercontent.com/18515874/39368359-a1a4376a-4a39-11e8-9490-84e5b44c4861.PNG)
But it seems that it is not so trivial to get the data from the selected item after the context menu was clicked. I will continue investigating and opened also a question about that in the MSDN community forum.

**Comment by bmgandre** [comment]
Ok. Thanks @Therena.

**Comment by Therena** [comment]
Found a solution to get it working.
Can you (@bmgandre) please also have a look on version 2.0.0.18 and give me feedback if it is how you would expect.

**Comment by Therena** [comment]
All my tests were successful. I didn't get so far any negative response which is great.
So I will close this now …

**Comment by bmgandre** [comment]
Great job! 
Thanks @Therena!
