### ISSUE TITLE
Open folder in ConEmu not changing if ComEmu pane is closed.

### ISSUE THREAD

**Issue by LBoullosa** [Therena/ConEmuIntegration#14]
Hello,

If ConEmu pane is closed and I use "Open folder in ConEmu" it opens a pane with ConEmu but not it doesn´t change to the folder. I was trying it with VStudio 2019 Community Edition

See image attached for an example,

![image](https://user-images.githubusercontent.com/44029921/70393025-2577c480-19e6-11ea-9388-bc4f500fc23b.png)

Thanks in advance,

**Comment by Therena** [comment]
Hey @LBoullosa,

can you please retry this with the latest version 2.2019.0.4.
For me this isn't reproducible with that version anymore.

Thank you.

Regards,
David
