### ISSUE TITLE
Use theme colors

### ISSUE THREAD

**Issue by m0sa** [Therena/ConEmuIntegration#2]
### Installed product versions
- Visual Studio: "15" Enterprise Preview 2
- This extension: 2.0.0.0

The extension's dialogs/tabs don't use colors from the currently active theme in Visual Studio

![image](https://cloud.githubusercontent.com/assets/503702/15314559/ef39a80e-1c12-11e6-8f99-68f9dcd3e628.png)

![image](https://cloud.githubusercontent.com/assets/503702/15314664/9748ce9e-1c13-11e6-8f9d-a146a30c55f4.png)

**Comment by Therena** [comment]
Hi,

thanks for reporting this issue.

The exception dialog is part of the extension and I will check if I can adapt it that it uses the colors of the color scheme.

But the conemu window is coming from the conemu project and I have no possibilities to change the colors there. The conemu console colors are changeable in the conemu configuration, but the tab panel cannot be changed as far I know.

This means I will check if I can change the colors of the exception dialog, but cannot change the color of the conemu panel.

I will take this as minor bug, bacause it only is about the exception window which should only be shown in exceptional cases.

Regards,
David

**Comment by Therena** [comment]
Since version 2.0.0.2 uses the exception dialog the Visual Studio color scheme.
Therefor this bug is fixed.
