### ISSUE TITLE
Crash when starting the extension

### ISSUE THREAD

**Issue by PhilipDaniels** [Therena/ConEmuIntegration#3]
### Installed product versions
- Visual Studio: 2015 Professional Update 2
- This extension: 2.0.0.5
### Description

When starting the extension (only tried it via View -> Other Windows -> ConEmu Console) I get a crash. After dismissing the crash notification dialogs, I can then repeat the above command and ConEmu opens correctly.
This only happens on my work laptop, on my home PC it does not happen.
### Steps to recreate
1. Open VS. Does not matter if there is a solution or not.
2. Go View -> Other Windows -> ConEmu Console
## Screenshots and Dumps

I have repeated the issue twice, and got some screenshots and dumps from ConEmu.

The first dump should be available here (69MB file):
https://drive.google.com/open?id=0B1Lj6ZmwOv0bb1JUZnpVVzJGQUU

Corresponding Images:
![trap-160218-17868_1](https://cloud.githubusercontent.com/assets/1809220/16409029/68589224-3d13-11e6-83ec-efc0a1337661.png)
![trap-160218-17868_2](https://cloud.githubusercontent.com/assets/1809220/16409034/6b7d52fa-3d13-11e6-898a-e85b0648ae06.png)

**Comment by PhilipDaniels** [comment]
Second dump (69MB file):

https://drive.google.com/open?id=0B1Lj6ZmwOv0bSXpUdWJKYk1JUlk

Images:
![trap-160218-10048_2](https://cloud.githubusercontent.com/assets/1809220/16409093/bfebd208-3d13-11e6-8953-e8f2896be6ba.png)
![trap-160218-10048_1](https://cloud.githubusercontent.com/assets/1809220/16409094/bfecb36c-3d13-11e6-9f81-bdef310b1d10.png)

**Comment by Therena** [comment]
Hi,

the assert error from your first post should be fixed in version 2.0.0.6 of the extension.

For the crash, from your second post, I have to ask the conemu team to give me more infromations, because I don't have any debug symbols of conemu.

Regards,
David

**Comment by Therena** [comment]
Hi,

for the crash (Your second post) I opened this:
https://github.com/Maximus5/conemu-inside/issues/28

Hope I get soon some imformation from conemu team to understand what is going wrong there.

Regards,
David

**Comment by Maximus5** [comment]
The "crash" has no sense because it's a result of "Retry" button in the Assertion dialog.

Anyway, you are using [OldBuild](https://conemu.github.io/en/OldBuild.html).

**Comment by Therena** [comment]
Hi,

I checked the dump after I got the symbols and as Maximus5 already told the dump tells the same as the assert message box.

STACK_TEXT: 
KERNELBASE!DebugBreak+0x2
ConEmu64!AssertBox+0x271
ConEmu64!CVConGroup::PreReSize+0x153
ConEmu64!CConEmuSize::SetWindowMode+0xc45
ConEmu64!CConEmuMain::PostCreate+0x12e
ConEmu64!WinMain+0x120a
ConEmu64!__tmainCRTStartup+0x189
kernel32!BaseThreadInitThunk+0x22
ntdll!RtlUserThreadStart+0x34

Therefor should the assert and the crash be fixed with the extension with the version 2.0.0.6.

@PhilipDaniels Please try again with the new version and tell me if the issue is solved.

@Maximus5 Thanks again for your time and the fast help. I really appreciate it.

Regards,
David

**Comment by PhilipDaniels** [comment]
Hi David,

Thanks for the quick response!

I have upgraded ConEmu (to 160619) and the add-in this morning. The crash appears to be fixed (it's a little early to tell for sure), however there is a regression.

1, Do View -> Other Windows -> ConEmu. You get a window showing the cmd prompt.
2. Open another ConEmu task. You now have two windows in ConEmu.
3. Close the first window by typing "exit".
4. The entire ConEmu window closes. It didn't used to do this (and is unexpected). I should still be seeing the ConEmu window displaying the task I started in 2).

**Comment by Maximus5** [comment]
@PhilipDaniels Are you sure ConEmu is closed? Have you checked its process in ProcessManager for example?

**Comment by PhilipDaniels** [comment]
@Maximus5 the **ConEmu integration window** in Visual Studio is definitely gone, but you are right, the ConEmu process is still there running in the background.

![procs](https://cloud.githubusercontent.com/assets/1809220/16445916/ec6fb960-3ddc-11e6-923d-3e1fe43db2c2.png)

Unfortunately I also got another crash while trying to reproduce this:

![crash1](https://cloud.githubusercontent.com/assets/1809220/16445921/f3828b88-3ddc-11e6-8333-a405f6458ec8.png)

So it looks like the original problem is not yet fixed.

**Comment by Therena** [comment]
@PhilipDaniels hmm ok this is bad. Then I have to check this again. Unfortunately I couldn't reproduce this on my system anymore. I will do so further investigation this evening.

**Comment by Maximus5** [comment]
@Therena A little offtopic. There is some crazyness in how VS manage its panes... If I dock ConEmu pane into the bottom area (to the other tabs, like build output) and start the debugger, ConEmu pane disappers (but is not destroyed) and debug panes appear. I wonder, can ConEmu pane remain visible while VS switches debug/design modes? That would be especially useful for debugging console applications.

**Comment by Therena** [comment]
@PhilipDaniels Waht version of conemu have you now installed? 
I have the extension 2.0.0.6 and ConEmu 160619 [32].
I cannot reproduce the assert issue anymore (In the short time frame I tested until now).
But maybe your version is different.

**Comment by PhilipDaniels** [comment]
@Therena It's in the screenshots above - 160619 [64]. The add-in is at 2.0.0.6.

Installed via chocolatey, not that that should make a difference. Also, you can see my ConEmu.xml here

https://github.com/PhilipDaniels/dotfiles/blob/master/ConEmu.xml

**Comment by Therena** [comment]
@PhilipDaniels Thanks I will try to set up the same this evening. It always easier to fix something if you can reproduce the issue ;)

**Comment by Therena** [comment]
@Maximus5 I moved your off topic to a dedicated enhancement: https://github.com/Therena/ConEmuIntegration/issues/4

**Comment by Therena** [comment]
@PhilipDaniels I have create an extra ticket for the unexpected close on the conemu pane: https://github.com/Therena/ConEmuIntegration/issues/5

**Comment by Therena** [comment]
I cannot reproduce the assert problem since the extension version 2.0.0.6
But I applied some more fixes that the pane cannot get a size of zero.

@PhilipDaniels Can you please retest with the extension 2.0.0.7?

**Comment by Therena** [comment]
@PhilipDaniels I reproduced the unexpected close and fix the issue.
See Bug: https://github.com/Therena/ConEmuIntegration/issues/5

**Comment by PhilipDaniels** [comment]
@Therena no crashes so far today! Don't close the issue yet, I will monitor for the next few days and close if it does not re-occur.

**Comment by Therena** [comment]
@PhilipDaniels ok, I will let it open for some time. Please keep me up to date.

**Comment by PhilipDaniels** [comment]
@Therena I think this can be closed now, I have not experienced any issues over the last few days.
