### ISSUE TITLE
Allow the initial ConEmu task to be specified

### ISSUE THREAD

**Issue by PhilipDaniels** [Therena/ConEmuIntegration#6]
It would be great if we could choose the initial task that is run when the ConEmu window is shown. There are several things to think about.

Firstly, ConEmu already has a startup task specified in ConEmu.xml. Why not just run that?

Secondly, we may want more flexibility when running ConEmu inside Visual Studio vs running it normally, in which case the first point is not valid. Instead, I should be allowed to pick a specific task to be the startup task within VS. The list of tasks is currently hardwired (to cmd and PS) but could instead be derived by parsing the ConEmu.xml file. As an example, lots of people may run Far Manager as their normal ConEmu startup task, but want to default to the VS2015 command prompt when running inside Visual Studio.

Thirdly, the "change directory" logic that runs when you open from the context-sensitive menu is great, but is hardcoded to two different types of shells (cmd.exe and powershell.exe). Other shells that are widely in use are cygwin (bash) and Git for Windows (bash again, but based on MinGW). The syntax will vary for different shells and it is a hard task to keep up with them all (though perhaps not infeasible). Interestingly, cygwin bash will allow **cd 'C:\Users\pdaniels'**, which is a bit of a surprise, it looks like somebody tought it to translate Windows paths to cygwin ones (that is really **/c/users/pdaniels** on my system due to how I have my cygdrive prefix set, but for normal Cygwin users would be **/cygdrive/c/users/pdaniels**). I haven't tested Git for Windows.

Alternatively, perhaps it is possible to adjust the cwd before starting the ConEmu window? Not sure if this is possible or not, it depends on how ConEmu process is invoked.

**Comment by Therena** [comment]
This cannot be solved in the extension only.

I opened a bug for this in the conemu inside project:
https://github.com/Maximus5/conemu-inside/issues/27

As long conemu or in this case conemu inside doesn't support this, it is not possible to add this to the extension.

**Comment by PhilipDaniels** [comment]
I think you should reference the Github issue I created as well because it
contains a lot more thinking about the subject.

On 1 July 2016 at 09:02, David Roller notifications@github.com wrote:

> This cannot be solved in the extension only.
> 
> I opened a bug for this in the conemu inside project:
> Maximus5/conemu-inside#27
> https://github.com/Maximus5/conemu-inside/issues/27
> 
> As long conemu or in this case conemu inside doesn't support this, it is
> not possible to add this to the extension.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Therena/ConEmuIntegration/issues/6#issuecomment-229882550,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABubRKQZODyO_LjvkDXCamg1nOQClA-Sks5qRMl9gaJpZM4JB-r6
> .

## 

Philip Daniels.

**Comment by Therena** [comment]
@PhilipDaniels Done :)

**Comment by Therena** [comment]
@PhilipDaniels I added a configuration in VS to give you the possibility to set the default task.  thin it would be even nicer in future to have the possibility to use the default task from the conemu XML configuration. Fo details please have a look in the conemu-inside bug.

**Comment by Therena** [comment]
For now this enhancement is done. 
The next steps will be part of the conemu-inside bug.

**Comment by PhilipDaniels** [comment]
This seems to be working, in that I can select a task by typing, such as {Sol Dark::Single}. I still think it would be better if you were to parse the xml file though, there is less chance of making a typo.

And the initial working directory does not appear to be set, which is a regression compared to previous versions when using the context-sensitive Open ConEmu menus in solution explorer.

**Comment by Therena** [comment]
@PhilipDaniels Yes I agree. But you know I am using the conemu-inside project to display conemu. If the conemu-inside doesn't support this, I am also not able to add this feature.

Or I have rebuild the conemu-inside project within the Visual Studio extension. Which I had in the first versions of the extension. The drawback of this is that the Visual Studio extension is the hardly dependent on the conemu version which will also cause big problems.

Even if the extension would read the tasks from the XML it would be problematic. Think about if the Conemu team decides to change the e.g. the structure of the settings file.

Because of this I closed this enhancement but not the bug in the conemu-inside project. 
If they have added the feature, I will also provide this in the extension.

Maybe it would help if you comment this in the bug of the conemu-inside project. That they see that there is really the need of such features.

Thanks for understanding.

**Comment by Therena** [comment]
> And the initial working directory does not appear to be set, which is a regression compared to 
> previous versions when using the context-sensitive Open ConEmu menus in solution explorer.

With the current conemu-inside version I only have the option to override all command line settings of conemu. So if you set the default task maybe also other settings get overridden.

I will check that ...
